on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      
      - name: Build and Pack
        run: |
          dotnet restore HIT.Vault/HIT.Vault.csproj
          dotnet build --configuration Release HIT.Vault/HIT.Vault.csproj /p:Version=$GITHUB_REF_NAME
          dotnet pack --configuration Release HIT.Vault/HIT.Vault.csproj --include-source /p:Version=$GITHUB_REF_NAME
          dotnet nuget add source --name hit-registry --store-password-in-clear-text --username ${{ secrets.FRENDS_NUGET_V2_FEED_USER }} --password "${{ secrets.FRENDS_NUGET_V2_FEED_KEY }}" ${{ secrets.FRENDS_NUGET_V2_FEED_URL }}
          dotnet nuget push --source hit-registry HIT.Vault/bin/Release/HIT.Vault.*.nupkg --skip-duplicate
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: HIT.Vault/bin/Release/*.nupkg
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          
